gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 43200            # 12 houre
  firewall: main
  token_parameter_name: refresh_token
  user_identity_field: username
  single_use: true      # ✅ chaque refresh génère un nouveau refresh_token
