gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 604800            # 7 days (in seconds)
  firewall: main
  token_parameter_name: refresh_token
  single_use: true       # each refresh token can only be used once (recommended)
